#pragma once

// Handedness //
#define EE_HANDS

// Split keyboard //
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 1500
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
// #define SPLIT_LED_STATE_ENABLE
// #define SPLIT_MODS_ENABLE
// #define SPLIT_WPM_ENABLE
#define SPLIT_OLED_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define SPLIT_TRANSACTION_IDS_KB KEYBOARD_CURRENT_ALPA_SYNC

// Layers //
#define LAYER_STATE_8BIT

// Combos //
#define COMBO_TERM 50
#define COMBO_ONLY_FROM_LAYER 0

// Tapping //
#define TAPPING_TERM 175

// Tap dance //
#define TAPPING_TERM_PER_KEY

// Oneshot //
#define NO_ACTION_ONESHOT

// RGB Matrix //
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL

#define RGB_TRIGGER_ON_KEYDOWN

#define RGB_MATRIX_SPLIT { 43, 43 }
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_TIMEOUT 60000
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_STARLIGHT
#define ENABLE_RGB_MATRIX_RIVERFLOW

// Music //
#define NO_MUSIC_MODE

// Lock key support //
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
