#pragma once

// Handedness //
#define EE_HANDS

// Split keyboard //
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 1500
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
// #define SPLIT_LED_STATE_ENABLE
// #define SPLIT_MODS_ENABLE
// #define SPLIT_WPM_ENABLE
#define SPLIT_OLED_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define SPLIT_TRANSACTION_IDS_KB KEYBOARD_CURRENT_ALPA_SYNC

// Leader key //
#define LEADER_NO_TIMEOUT
#define LEADER_TIMEOUT 175
#define LEADER_PER_KEY_TIMING

// Tap dance //
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY

// RGB Matrix //
#ifdef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#endif

#ifdef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#endif

#define RGB_MATRIX_SLEEP
#define RGB_TRIGGER_ON_KEYDOWN
#define RGB_MATRIX_SPLIT { 43, 43 }
#define RGB_MATRIX_TIMEOUT 30000
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_NONE

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_STARLIGHT
#define ENABLE_RGB_MATRIX_RIVERFLOW
